apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}"
type: Opaque
stringData:
  ACCESS_TOKEN_SECRET_KEY: "{{ .Values.secrets.token.access_key }}"
  REFRESH_TOKEN_SECRET_KEY: "{{ .Values.secrets.token.refresh_key }}"

  ZVONOK_API_PUBLIC_KEY: "{{ .Values.secrets.zvonok.api_key }}"
  ZVONOK_CAMPAIGN_ID: "{{ .Values.secrets.zvonok.campaign_id }}"

  DB_USER: "{{ .Values.secrets.postgres.username }}"
  DB_PASSWORD: "{{ .Values.secrets.postgres.password }}"

  RABBITMQ_USER: "{{ .Values.secrets.rabbit.username }}"
  RABBITMQ_PASSWORD: "{{ .Values.secrets.rabbit.password }}"

  SMTP_PASSWORD: "{{ .Values.secrets.smtp.password }}"

  SBER_DB_KEY: "{{ .Values.secrets.sber.sberDbKey }}"
  SBER_DV_IV: "{{ .Values.secrets.sber.sberDbIv }}"

  NEWTEL_API_KEY: "{{ .Values.secrets.newtel.apiKey }}"
  NEWTEL_WRITE_KEY: "{{ .Values.secrets.newtel.writeKey }}"

  SBER_CERT_PASS: "{{ .Values.secrets.sber.certPass }}"
