apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-sber"
type: Opaque
data:
  tls.cer: "{{ .Values.tls.cer }}"
  tls.pfx: "{{ .Values.tls.pfx }}"
  sberca_root_ext.crt: "{{ .Values.sberca_root_ext.crt }}"
  sberca_ext.crt: "{{ .Values.sberca_ext.crt }}"
  Sberbank_Root_CA.cer: "{{ .Values.Sberbank_Root_CA.cer }}"
  sberapi_root_ca.cer: "{{ .Values.sberapi_root_ca.cer }}"
  sberapi_ca.cer: "{{ .Values.sberapi_ca.cer }}"
